    #  Processing Parameters
    layer_name: layer1    # - Selected Offsets layer
    metric:  median_filter    # - Outlier selection method
    threshold: 10             # - Outlier selection threshold
    window_az: 51             # - Outlier selection window size - Azimuth
    window_rg: 51             # - Outlier selection window size - Range
